# #15. icp 설치 관련
- name: 15. Preset ICP install'
  hosts: 'boot'
  gather_facts: true
  remote_user: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_id }}{% endif %}{% endfor %}{% endfor %}'
  vars_files:
    - ../../automation_config.yaml
 
  vars:
    ansible_become: true
    ansible_user: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_id }}{% endif %}{% endfor %}{% endfor %}'
    #pem key를 사용하는 경우
    ansible_ssh_private_key_file: '{{ util.pemkey }}'
    #password를 사용하는 경우
    ansible_ssh_pass: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_pwd }}{% endif %}{% endfor %}{% endfor %}'
    ansible_become_pass: "{{ ansible_ssh_pass }}"
    ansible_ssh_common_args: "-oPubkeyAuthentication=no"
    icp_install_path: '/opt/ibm-cloud-private-{{ util.icp_ver }}'

  tasks:
 #cluster/runtime 추가 할것
    - name: '15-1. Make install image directory'
      file:
        path: '{{ item.path }}'
        state: 'directory'
        mode: 'u=rw,g=r,o=r'
      with_items:
        - { path: '{{ icp_install_path }}/cluster/images' }
        - { path: '{{ icp_install_path }}/cluster/runtime' }
      register: 'result'
    - debug:
        var: 'result.stdout'