# #17. icp 설치 관련
- name: 17. Preset ICP install'
  hosts: 'boot'
  gather_facts: true
  remote_user: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_id }}{% endif %}{% endfor %}{% endfor %}'
  vars_files:
    - ../../automation_config.yaml
 
  vars:
    ansible_become: true
    ansible_user: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_id }}{% endif %}{% endfor %}{% endfor %}'
    #pem key를 사용하는 경우
    ansible_ssh_private_key_file: '{{ util.pemkey }}'
    #password를 사용하는 경우
    ansible_ssh_pass: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_pwd }}{% endif %}{% endfor %}{% endfor %}'
    ansible_become_pass: "{{ ansible_ssh_pass }}"
    ansible_ssh_common_args: "-oPubkeyAuthentication=no"
    icp_install_path: '/opt/ibm-cloud-private-{{ util.icp_ver }}'

  tasks:
  #config.yaml은 미리 작성 후, 불러오기
 # 18. cluster 설정 (cluster/config.yaml)
    - name: '17-1. move folder config.yaml'
      shell: 'mv {{ util.config_path }} {{ icp_install_path }}/cluster/'                
      register: 'result'