- name: '3. Install, NTP Check '
  hosts: 'all'
  gather_facts: true
  remote_user: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_id }}{% endif %}{% endfor %}{% endfor %}'
  vars_files:
    - ../../automation_config.yaml

  vars:
    ansible_become: true
    ansible_user: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_id }}{% endif %}{% endfor %}{% endfor %}'
    #pem key를 사용하는 경우
    ansible_ssh_private_key_file: '{{ util.pemkey }}'
    #password를 사용하는 경우
    ansible_ssh_pass: '{% for name, item in node.items() %}{% for value in item %}{% if inventory_hostname == value.name %}{{ value.user_pwd }}{% endif %}{% endfor %}{% endfor %}'
    ansible_become_pass: "{{ ansible_ssh_pass }}"
    ansible_ssh_common_args: "-oPubkeyAuthentication=no"

  tasks:
    - name: '3-1. Install epel package'
      yum:
        name:
          - epel-release
        state: 'present'
      delay: 10
      retries: 3
      register: result
      ignore_errors: yes
      until: result is succeeded 

    - name: '3-2. Run task port check'
      shell: 'ss -tnlp | awk "{print $4}" | egrep -w "8001|8500|3306"' 
      register: result
      failed_when: result.stdout != "" 